allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - icu-minify@4.14.5
  - next-intl-swc-plugin-extractor@4.14.5
  - next-intl@4.14.5
  - use-intl@4.14.5
  - zod@4.6.5
